---
title: "Qfish Assignment"
author: "Jack Ochtman"
date: "2025-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install tidyverse and janitor packages.

```{r setup echo = T, results = 'hide'}
# Install and load tidyverse, run if needed.
#install.packages("tidyverse")
#library("tidyverse")
#install.packages("janitor")
#library("janitor")
```


```{r load file echo = T, results = 'hide'}
shark <- read_csv("../data/shark_size.csv") |>
  row_to_names(row_number = 1, remove_rows_above = FALSE) |>
  clean_names()
shark
```


```{r load file echo = T, results = 'hide'}
shark_size <- 
  shark |>
  rename(year = financial_year, small = x2m, large=x2m_2) |>
  mutate(year = as.numeric(sub(".*-(\\d{2})", "20\\1", year)))
shark_size
```


```{r load file echo = T, results = 'hide'}
shark_size <- 
  shark_size |>
  mutate_at(vars(small, large), as.numeric)
shark_size
```


```{r load file echo = T, results = 'hide'}
shark_size <- 
  shark_size |>
  filter(!is.na(year))
shark_size
```


```{r load file echo = T, results = 'hide'}
shark_size <- shark_size %>%
  filter(area != "Bribie Island") %>%
  filter(area != "Sunshine Coast South & Bribie Island") %>%
  filter(area != "Sunshine Coast South")
shark_size
```


```{r load file echo = T, results = 'hide'}
shark_size <- shark_size %>%
  mutate(across(where(is.numeric), ~replace_na(., 0)))
shark_size
```


```{r load file echo = T, results = 'show'}
ggplot(shark_size, aes(x = year, y = small, color = area)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
    theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) +
    labs(title = "Catch of <2m Sharks by Location",
  x = "Year",
  y = "No. of <2m Sharks Caught")
```

```{r load file echo = T, results = 'show'}
ggplot(shark_size, aes(x = year, y = large, color = area)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
    theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) +
    labs(title = "Catch of ≥m Sharks by Location",
  x = "Year",
  y = "No. of ≥2m Sharks Caught")
```


```{r load file echo = T, results = 'show'}
facet_plot <- ggplot() +
  geom_line(data = shark_size, aes(x = year, y = small, color = "<2m"), linewidth = 0.25) +
  geom_line(data = shark_size, aes(x = year, y = large, color = "≥2m"), linewidth = 0.25) +
  geom_point(data = shark_size, aes(x = year, y = small, color = "<2m"), shape = 16, size = 1) +
  geom_point(data = shark_size, aes(x = year, y = large, color = "≥2m"), shape = 17, size = 1) +
  facet_wrap(~ area) +
  scale_color_manual(values = c("<2m" = "#E69F00", "≥2m" = "#56B4E9")) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "white"),
    strip.background = element_rect(fill = "white"),
    axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Catch of Sharks by Size and Location",
    x = "Year",
    y = "No. of Sharks Caught",
    color = "Shark Size")

ggsave("../plots/shark_catch_plot.png", plot = facet_plot, width = 8, height = 6, dpi = 300)

print(facet_plot)
```
